{
 "title": "MedicPUCP - Por Usuario",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Datos",
    "label": "DATOS",
    "query": "-- NO REVISADO POR QUERY DE TIMESCALEDB\nSELECT CONCAT(auth_user.first_name,' ', auth_user.last_name,' DNI:',api_medic_kit_per_user.kit_id) AS variables\nFROM auth_user\nINNER JOIN api_medic_kit_per_user ON auth_user.id = api_medic_kit_per_user.user_id\nINNER JOIN api_medic_hypertable ON api_medic_kit_per_user.kit_id=api_medic_hypertable.kit_id\nGROUP BY api_medic_kit_per_user.user_id,auth_user.id,api_medic_kit_per_user.kit_id;"
   },
   {
    "name": "kit_id",
    "label": "KIT_ID",
    "query": "SELECT DISTINCT kit_id FROM api_medic_hypertable"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "content": "\n# Bienvenido a MedicPUCP\n\nRangos normales:\n- Presión cardíaca `[75,110]`\n- Frecuencia respiratoria `[12,22]`\n- Temperatura corporal `[35.5,37.5]`\n\n`Debes seleccionar almenos un kit_id`\n\n\n"
  },
  {
   "title": "KIT_ID=$kit_id - Temperatura corporal",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  temp_corp\nFROM api_medic_hypertable\nWHERE\n  $__timeFilter(\"time\") AND\n  kit_id = '$kit_id'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "KIT_ID=$kit_id - Frecuencia respiratoria",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  frec_resp\nFROM api_medic_hypertable\nWHERE\n  $__timeFilter(\"time\") AND\n  kit_id = '$kit_id'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "KIT_ID=$kit_id - Presión cardíaca",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  pres_card\nFROM api_medic_hypertable\nWHERE\n  $__timeFilter(\"time\") AND\n  kit_id = '$kit_id'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "KIT_ID: $kit_id - Signos vitales en tiempo real",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 7, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  pres_card,\n  frec_resp,\n  temp_corp\nFROM api_medic_hypertable\nWHERE\n  $__timeFilter(\"time\") AND\n  kit_id = '$kit_id'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "KIT_ID=$kit_id - Últimos sensados del kit",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT time as \"Últimos Reportes\" FROM api_medic_hypertable ORDER BY time DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Batería Medikit $kit_id",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT api_medic_kit_per_user.estado_baterias , js.key, js.value\r\nFROM api_medic_kit_per_user, json_each(api_medic_kit_per_user.estado_baterias) AS js\r\nWHERE api_medic_kit_per_user.kit_id='$kit_id' AND js.key='bateria_medikit';"
    }
   ]
  },
  {
   "title": "Batería Mediband $kit_id",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 15, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT api_medic_kit_per_user.estado_baterias , js.key, js.value\r\nFROM api_medic_kit_per_user, json_each(api_medic_kit_per_user.estado_baterias) AS js\r\nWHERE api_medic_kit_per_user.kit_id='$kit_id' AND js.key='bateria_mediband';"
    }
   ]
  }
 ]
}