{
 "title": "Dashboard to alert",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "content": "\n# Alertas MedicPUCP\n\nRangos normales:\n- Presión cardíaca `[75,110]`\n- Frecuencia respiratoria `[12,22]`\n- Temperatura corporal `[35.5,38.0]`\n\n\n"
  },
  {
   "title": "Alerta - Presion Cardíaca",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "mmHg" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  pres_card,\n  kit_id\nFROM api_medic_hypertable\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1\nLIMIT 512"
    }
   ]
  },
  { "title": "Últimas alertas", "type": "alertlist", "gridPos": { "h": 13, "w": 6, "x": 0, "y": 5 } },
  {
   "title": "Alerta - Frecuencia respiratoria",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "respiración / minuto" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  frec_resp,\n  kit_id\nFROM api_medic_hypertable\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1\nLIMIT 512"
    }
   ]
  },
  {
   "title": "Alerta - Temperatura corporal",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  temp_corp,\n  kit_id\nFROM api_medic_hypertable\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1\nLIMIT 512"
    }
   ]
  }
 ]
}